# Inspired by https://docs.docker.com/compose/django/
version: '3.4'

services:
  db:
    image: postgres:11-alpine
    # environment:
    #   - POSTGRES_USER=${PG_USER:{{ project_name|lower }}}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:{{ project_name|lower }}}
  web:
    image: vngr/gemma-{{ project_name|lower }}
    environment:
      - DJANGO_SETTINGS_MODULE={{ project_name|lower }}.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db
