---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ project_name|lower }}
  namespace: gemma
  labels:
    k8s-app: {{ project_name|lower }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ project_name|lower }}
  template:
    metadata:
      name: {{ project_name|lower }}
      labels:
        k8s-app: {{ project_name|lower }}
    spec:
      containers:
      - name: {{ project_name|lower }}
        image: vngr/vng-referentielijsten:0.1.0
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: {{ project_name|lower }}.conf.docker
          - name: SUBPATH
            value: /referentielijsten
          - name: DB_HOST
            value: postgres-{{ project_name|lower }}
          - name: SECRET_KEY
            value: <REDACTED>
          - name: DB_PASSWORD
            value: <REDACTED>
          - name: SENTRY_DSN
            value: <REDACTED>

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: {{ project_name|lower }}
  namespace: gemma
  labels:
    k8s-app: {{ project_name|lower }}
spec:
  selector:
    k8s-app: {{ project_name|lower }}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
